// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewkjzzsqbuljftfgfmnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3a2p6enNxYnVsamZ0ZmdmbW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTE2OTQsImV4cCI6MjA3MzQyNzY5NH0.Jjc8ZCc192V3zEHB7CxnF0jCg7pixG-uq8tjo_a__CM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});